service:
  name: "ruby-api-gateway"

plugins:

provider:
  name: aws
  runtime: ruby2.5
  profile: ${file(../serverless.yml):provider.profile}
  region: ${file(../serverless.yml):provider.region}
  stage: ${file(../serverless.yml):provider.stage}
  apiGatewayRestApiName: ${file(../serverless.yml):provider.apiGatewayRestApiName}

  environment:
#    CHANGE_VALUE: ${env:CHANGE_VALUE, file(../serverless.yml):provider.environment.CHANGE_VALUE}

package:
  include:
    - ./.gitignore
    - ./src/**
  exclude:
    - ./**


functions:
  # list
  getChanges:
    handler: src/handler.get_changes
    events:
      - http:
          method: get
          path: changes
          cors: true
custom:
  user: ${file(../serverless.yml):custom.user}
  localDevPort: 5000